In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

from subprocess import check_output
#print(check_output(["ls", "../input"]).decode("utf8"))

# Any results you write to the current directory are saved as output.

In [34]:
submission = pd.read_csv('input/stage2_sample_submission.csv')
stage1_test = pd.read_csv('input/test_variants')
stage2_test = pd.read_csv('input/test_variants.csv')
stage1_solution = pd.read_csv('input/stage1_solution_filtered.csv')

stage1_solution = stage1_solution.merge(stage1_test, how = 'left', on = 'ID')

stage2_test.merge(
        stage1_solution.drop('ID', axis = 1), 
        how = 'left', 
        on = ['Gene', 'Variation'])\
    .drop(['Gene', 'Variation'], axis = 1)\
    .fillna(0.99)\
    .to_csv('submission_0.99.csv', index = False)

In [33]:
submission

,ID,class1,class2,class3,class4,class5,class6,class7,class8,class9
0,1,1,1,1,1,1,1,1,1,1
1,2,1,1,1,1,1,1,1,1,1
2,3,1,1,1,1,1,1,1,1,1
3,4,1,1,1,1,1,1,1,1,1
4,5,1,1,1,1,1,1,1,1,1
5,6,1,1,1,1,1,1,1,1,1
6,7,1,1,1,1,1,1,1,1,1
7,8,1,1,1,1,1,1,1,1,1
8,9,1,1,1,1,1,1,1,1,1
9,10,1,1,1,1,1,1,1,1,1
10,11,1,1,1,1,1,1,1,1,1
11,12,1,1,1,1,1,1,1,1,1
12,13,1,1,1,1,1,1,1,1,1
13,14,1,1,1,1,1,1,1,1,1
14,15,1,1,1,1,1,1,1,1,1
15,16,1,1,1,1,1,1,1,1,1
16,17,1,1,1,1,1,1,1,1,1
17,18,1,1,1,1,1,1,1,1,1
18,19,1,1,1,1,1,1,1,1,1
19,20,1,1,1,1,1,1,1,1,1
20,21,1,1,1,1,1,1,1,1,1
21,22,1,1,1,1,1,1,1,1,1
22,23,1,1,1,1,1,1,1,1,1
23,24,1,1,1,1,1,1,1,1,1
24,25,1,1,1,1,1,1,1,1,1
25,26,1,1,1,1,1,1,1,1,1
26,27,1,1,1,1,1,1,1,1,1
27,28,1,1,1,1,1,1,1,1,1
28,29,1,1,1,1,1,1,1,1,1
29,30,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...
956,957,1,1,1,1,1,1,1,1,1
957,958,1,1,1,1,1,1,1,1,1
958,959,1,1,1,1,1,1,1,1,1
959,960,1,1,1,1,1,1,1,1,1
960,961,1,1,1,1,1,1,1,1,1
961,962,1,1,1,1,1,1,1,1,1
962,963,1,1,1,1,1,1,1,1,1
963,964,1,1,1,1,1,1,1,1,1
964,965,1,1,1,1,1,1,1,1,1
965,966,1,1,1,1,1,1,1,1,1
966,967,1,1,1,1,1,1,1,1,1
967,968,1,1,1,1,1,1,1,1,1
968,969,1,1,1,1,1,1,1,1,1
969,970,1,1,1,1,1,1,1,1,1
970,971,1,1,1,1,1,1,1,1,1
971,972,1,1,1,1,1,1,1,1,1
972,973,1,1,1,1,1,1,1,1,1
973,974,1,1,1,1,1,1,1,1,1
974,975,1,1,1,1,1,1,1,1,1
975,976,1,1,1,1,1,1,1,1,1
976,977,1,1,1,1,1,1,1,1,1
977,978,1,1,1,1,1,1,1,1,1
978,979,1,1,1,1,1,1,1,1,1
979,980,1,1,1,1,1,1,1,1,1
980,981,1,1,1,1,1,1,1,1,1
981,982,1,1,1,1,1,1,1,1,1
982,983,1,1,1,1,1,1,1,1,1
983,984,1,1,1,1,1,1,1,1,1
984,985,1,1,1,1,1,1,1,1,1
985,986,1,1,1,1,1,1,1,1,1

In [32]:
for i in range (9):
    submission['class'+str(i+1)]=1
submission.to_csv('submission_all1.csv', index = False)